// Word bank for generated puzzles: [ANSWER, clue]. Answers are A–Z only, 3–10 letters.
// Add more lines to get more variety — the generator picks from all of them.
export default [
  // 3 letters
  ["ACE", "Top card in many games"],
  ["AGE", "Number of candles on a cake"],
  ["AIR", "What we breathe"],
  ["ANT", "Tiny picnic pest"],
  ["APE", "Gorilla or chimp"],
  ["ARM", "Limb with an elbow"],
  ["ART", "Paintings and sculpture"],
  ["ASH", "What's left after a fire"],
  ["BAT", "Cricket club, or a night flyer"],
  ["BEE", "Honey maker"],
  ["BOW", "Archer's weapon, or a gift ribbon"],
  ["BUS", "Public transport with many stops"],
  ["CAB", "Taxi"],
  ["CUP", "Tea holder"],
  ["DEW", "Morning moisture on grass"],
  ["EAR", "Organ of hearing"],
  ["EEL", "Slippery snake-like fish"],
  ["EGG", "Breakfast item that can be scrambled"],
  ["ELF", "Santa's little helper"],
  ["EMU", "Large flightless Australian bird"],
  ["ERA", "Long period of history"],
  ["EYE", "Organ of sight"],
  ["FAN", "Cooling device, or a supporter"],
  ["FIG", "Sweet fruit, often dried"],
  ["FOX", "Sly animal with a bushy tail"],
  ["GEM", "Precious stone"],
  ["HAT", "Head covering"],
  ["HEN", "Female chicken"],
  ["ICE", "Frozen water"],
  ["INK", "Pen filler"],
  ["IVY", "Climbing plant on old walls"],
  ["JAM", "Fruit spread, or a traffic hold-up"],
  ["JAR", "Glass container with a lid"],
  ["JOY", "Great happiness"],
  ["KEY", "It opens a lock"],
  ["KIT", "Set of tools or equipment"],
  ["LAP", "One circuit of a track"],
  ["LID", "Pot cover"],
  ["MAP", "Guide for a road trip"],
  ["MUD", "Wet earth"],
  ["NAP", "Short sleep"],
  ["NET", "Goalkeeper guards it"],
  ["OAK", "Tree that grows from an acorn"],
  ["OAR", "Rowing blade"],
  ["OWL", "Wise night bird"],
  ["PAN", "Frying vessel"],
  ["PEA", "Small green vegetable in a pod"],
  ["PEN", "Writing tool"],
  ["PIE", "Baked dish with a crust"],
  ["RAY", "Beam of light"],
  ["RUG", "Small carpet"],
  ["SEA", "Large body of salt water"],
  ["SKY", "Where clouds float"],
  ["SUN", "Star at the centre of our solar system"],
  ["TEA", "Hot drink, often with milk"],
  ["TOE", "One of five on a foot"],
  ["VAN", "Delivery vehicle"],
  ["WEB", "Spider's creation"],
  ["YAM", "Starchy tuber, pounded in West Africa"],
  ["ZOO", "Place to see lions and giraffes"],
  // 4 letters
  ["ACRE", "Unit of land area"],
  ["ALOE", "Soothing plant for sunburn"],
  ["ARCH", "Curved structure over a doorway"],
  ["AREA", "Length times width"],
  ["ATOM", "Smallest unit of an element"],
  ["AUNT", "Parent's sister"],
  ["BAKE", "Cook in an oven"],
  ["BALL", "Round thing to kick or throw"],
  ["BARN", "Farm building"],
  ["BEAR", "Large furry animal that hibernates"],
  ["BELL", "It rings"],
  ["BIRD", "Feathered flyer"],
  ["BOAT", "It floats on water"],
  ["BONE", "Part of a skeleton"],
  ["BOOK", "Novel, for example"],
  ["CAKE", "Birthday dessert"],
  ["CAVE", "Bat's home"],
  ["CHEF", "Head cook"],
  ["CITY", "Lagos or London"],
  ["CLAY", "Potter's material"],
  ["COIN", "Piece of money"],
  ["CORN", "Maize"],
  ["DART", "Small arrow thrown at a board"],
  ["DATE", "Romantic outing, or a sweet fruit"],
  ["DEER", "Animal with antlers"],
  ["DESK", "Office table"],
  ["DOVE", "Bird of peace"],
  ["DRUM", "Instrument you beat"],
  ["DUCK", "Quacking bird"],
  ["DUNE", "Desert sand hill"],
  ["ECHO", "Sound that comes back"],
  ["EDGE", "Border or rim"],
  ["EXIT", "Way out"],
  ["FARM", "Place with crops and livestock"],
  ["FERN", "Leafy plant that reproduces by spores"],
  ["FIRE", "It needs heat, fuel and oxygen"],
  ["FISH", "Swimmer with gills"],
  ["FLAG", "National banner"],
  ["FOAM", "Bubbles on a latte"],
  ["FROG", "Croaking amphibian"],
  ["GAME", "Something to play"],
  ["GATE", "Garden entrance"],
  ["GIFT", "Present"],
  ["GOAL", "Aim, or a score in football"],
  ["GOLD", "Winner's medal"],
  ["HARP", "Stringed instrument played by angels"],
  ["HAWK", "Bird of prey"],
  ["HERO", "Brave person"],
  ["HIVE", "Bee's home"],
  ["HOPE", "Wish for something good"],
  ["IDEA", "Light-bulb moment"],
  ["IRON", "Metal, or a tool for clothes"],
  ["ISLE", "Small island"],
  ["JAZZ", "Music style with improvisation"],
  ["KITE", "It flies on a string"],
  ["KNOT", "Tie in a rope"],
  ["LAKE", "Inland body of water"],
  ["LAMP", "Reading light"],
  ["LEAF", "Green part of a tree"],
  ["LIME", "Green citrus fruit"],
  ["LION", "King of the jungle"],
  ["LOVE", "Deep affection"],
  ["MILK", "White drink from cows"],
  ["MINT", "Fresh herb"],
  ["MOON", "It orbits the Earth"],
  ["NEST", "Bird's home"],
  ["NOTE", "Short message, or a musical sound"],
  ["OPAL", "Iridescent gemstone"],
  ["OVEN", "Kitchen appliance for roasting"],
  ["PALM", "Tropical tree, or part of a hand"],
  ["PARK", "Green space in a city"],
  ["PEAR", "Fruit shaped like a light bulb"],
  ["POEM", "Verse"],
  ["RAIN", "Water falling from clouds"],
  ["RICE", "Jollof base"],
  ["RING", "Wedding band"],
  ["ROAD", "Street"],
  ["ROSE", "Flower with thorns"],
  ["SAIL", "Canvas on a yacht"],
  ["SALT", "Seasoning from the sea"],
  ["SAND", "Beach material"],
  ["SEED", "Plant starter"],
  ["SHIP", "Large ocean vessel"],
  ["SNOW", "White winter flakes"],
  ["SOAP", "Bath bar"],
  ["SOUP", "Hot liquid meal"],
  ["STAR", "Twinkler in the night sky"],
  ["SWAN", "Graceful white water bird"],
  ["TENT", "Camping shelter"],
  ["TIDE", "Rise and fall of the sea"],
  ["TOAD", "Warty amphibian"],
  ["TREE", "Oak or palm"],
  ["TUNE", "Melody"],
  ["VASE", "Flower holder"],
  ["VOTE", "Choose at an election"],
  ["WAVE", "Ocean swell, or a hand greeting"],
  ["WIND", "Moving air"],
  ["WOLF", "Howling wild dog"],
  ["YARN", "Knitting thread, or a long story"],
  ["ZERO", "Nothing"],
  // 5 letters
  ["ACORN", "Oak tree's seed"],
  ["ADORE", "Love deeply"],
  ["ALARM", "Morning wake-up sound"],
  ["ANGEL", "Heavenly messenger"],
  ["APPLE", "Fruit that fell on Newton"],
  ["APRIL", "Month after March"],
  ["ARROW", "Archer's projectile"],
  ["BEACH", "Sandy shore"],
  ["BERRY", "Small juicy fruit"],
  ["BLAZE", "Large fire"],
  ["BLOOM", "Flower"],
  ["BRAVE", "Courageous"],
  ["BREAD", "Loaf"],
  ["BRICK", "Building block"],
  ["BRUSH", "Painter's tool"],
  ["CABIN", "Small wooden house"],
  ["CAMEL", "Desert animal with a hump"],
  ["CANOE", "Paddled boat"],
  ["CHAIR", "Seat with a back"],
  ["CHALK", "Blackboard writer"],
  ["CHESS", "Game with kings and pawns"],
  ["CLOCK", "Timekeeper on the wall"],
  ["CLOUD", "White puff in the sky"],
  ["CORAL", "Reef builder"],
  ["CRANE", "Long-necked bird, or a building machine"],
  ["CROWN", "Royal headwear"],
  ["DAISY", "White flower with a yellow centre"],
  ["DANCE", "Move to music"],
  ["DREAM", "Story your mind tells while you sleep"],
  ["EAGLE", "National bird of the USA"],
  ["EARTH", "Our planet"],
  ["ELBOW", "Arm joint"],
  ["FAIRY", "Tiny winged creature in tales"],
  ["FEAST", "Large celebratory meal"],
  ["FENCE", "Garden boundary"],
  ["FIELD", "Open grassy land"],
  ["FLAME", "Candle's light"],
  ["FLUTE", "Woodwind instrument held sideways"],
  ["FROST", "Icy coating on a winter morning"],
  ["FRUIT", "Mango or banana"],
  ["GHOST", "Spooky spirit"],
  ["GIANT", "Huge person in a fairy tale"],
  ["GLOBE", "Spherical map"],
  ["GRAPE", "Wine fruit"],
  ["GUAVA", "Tropical fruit with pink flesh"],
  ["HEART", "Organ that pumps blood"],
  ["HONEY", "Sweet stuff made by bees"],
  ["HORSE", "Animal you ride"],
  ["HOTEL", "Place to stay on holiday"],
  ["HOUSE", "Home"],
  ["IGLOO", "Snow house"],
  ["JEANS", "Denim trousers"],
  ["JEWEL", "Precious gem"],
  ["JUICE", "Squeezed fruit drink"],
  ["KOALA", "Australian tree-hugger"],
  ["LEMON", "Sour yellow fruit"],
  ["LIGHT", "Opposite of dark"],
  ["LLAMA", "South American woolly animal"],
  ["MAGIC", "Wizard's art"],
  ["MANGO", "Sweet tropical fruit"],
  ["MAPLE", "Tree on Canada's flag"],
  ["MEDAL", "Olympic prize"],
  ["MELON", "Large juicy fruit"],
  ["MONEY", "Cash"],
  ["MOUSE", "Computer pointer, or a small rodent"],
  ["MUSIC", "Songs and melodies"],
  ["NIGHT", "Time after sunset"],
  ["NURSE", "Hospital carer"],
  ["OCEAN", "Atlantic or Pacific"],
  ["OLIVE", "Small fruit pressed for oil"],
  ["ONION", "Vegetable that makes you cry"],
  ["ORBIT", "Path around a planet"],
  ["OTTER", "Playful river animal"],
  ["PAINT", "Artist's colour"],
  ["PARTY", "Celebration"],
  ["PEACE", "Absence of war"],
  ["PEARL", "Gem from an oyster"],
  ["PIANO", "Instrument with 88 keys"],
  ["PILOT", "Plane flyer"],
  ["PIZZA", "Italian dish with toppings"],
  ["PLANT", "Living thing that grows in soil"],
  ["QUEEN", "Female monarch"],
  ["QUIET", "Hushed"],
  ["RADIO", "Device for listening to stations"],
  ["RAVEN", "Large black bird"],
  ["RIVER", "Flowing water like the Niger"],
  ["ROBOT", "Mechanical helper"],
  ["SALAD", "Leafy dish"],
  ["SHARK", "Ocean predator with fins"],
  ["SHEEP", "Wool animal"],
  ["SHELL", "Turtle's armour"],
  ["SMILE", "Happy expression"],
  ["SNAKE", "Slithering reptile"],
  ["SPOON", "Soup utensil"],
  ["STORM", "Thunder and lightning"],
  ["STORY", "Tale"],
  ["SUGAR", "Sweetener"],
  ["SWEET", "Like candy"],
  ["TABLE", "Furniture for dining"],
  ["TIGER", "Striped big cat"],
  ["TOAST", "Browned bread, or a raised glass"],
  ["TORCH", "Flashlight"],
  ["TOWER", "Tall structure"],
  ["TRAIN", "Railway vehicle"],
  ["TRUST", "Faith in someone"],
  ["TULIP", "Spring flower linked to Holland"],
  ["UNCLE", "Parent's brother"],
  ["VOICE", "Singer's instrument"],
  ["WATER", "H2O"],
  ["WHALE", "Largest sea mammal"],
  ["WORLD", "Planet Earth"],
  ["ZEBRA", "Striped horse-like animal"],
  // 6 letters
  ["ANCHOR", "It keeps a ship in place"],
  ["ANSWER", "Reply to a question"],
  ["ARTIST", "Painter or sculptor"],
  ["AUTUMN", "Season of falling leaves"],
  ["BANANA", "Yellow fruit monkeys love"],
  ["BASKET", "Woven carrier"],
  ["BEAUTY", "Loveliness"],
  ["BOTTLE", "Container for water"],
  ["BRIDGE", "Structure over a river"],
  ["BUTTER", "Spread on toast"],
  ["CACTUS", "Prickly desert plant"],
  ["CAMERA", "Device for taking photos"],
  ["CANDLE", "Wax light"],
  ["CARROT", "Orange vegetable rabbits love"],
  ["CASTLE", "Fortress with turrets"],
  ["CHERRY", "Small red fruit on a stalk"],
  ["CIRCLE", "Round shape"],
  ["COFFEE", "Morning brew"],
  ["COOKIE", "Sweet biscuit"],
  ["COTTON", "Soft fabric from a plant"],
  ["DESERT", "Sahara, for one"],
  ["DINNER", "Evening meal"],
  ["DOCTOR", "Physician"],
  ["DRAGON", "Fire-breathing beast"],
  ["ENERGY", "Power"],
  ["FAMILY", "Parents and children"],
  ["FATHER", "Dad"],
  ["FLOWER", "Bloom"],
  ["FOREST", "Large area of trees"],
  ["FRIEND", "Pal"],
  ["GARDEN", "Place to grow flowers"],
  ["GINGER", "Spicy root"],
  ["GUITAR", "Six-stringed instrument"],
  ["HAMMER", "Tool for nails"],
  ["HONEST", "Truthful"],
  ["INSECT", "Six-legged creature"],
  ["ISLAND", "Land surrounded by water"],
  ["JACKET", "Short coat"],
  ["JUNGLE", "Tropical rainforest"],
  ["KITTEN", "Young cat"],
  ["LADDER", "Climbing frame with rungs"],
  ["LAPTOP", "Portable computer"],
  ["LEGEND", "Famous old story"],
  ["LETTER", "A, B or C"],
  ["MARKET", "Place to buy and sell"],
  ["MIRROR", "It shows your reflection"],
  ["MONKEY", "Primate that swings in trees"],
  ["MOTHER", "Mum"],
  ["NATURE", "The natural world"],
  ["ORANGE", "Citrus fruit, or a colour"],
  ["PALACE", "Royal residence"],
  ["PARROT", "Talking bird"],
  ["PENCIL", "Writing tool with an eraser"],
  ["PEPPER", "Hot spice"],
  ["PLANET", "Mars or Venus"],
  ["POCKET", "Pouch in trousers"],
  ["PUZZLE", "This, for example"],
  ["RABBIT", "Bunny"],
  ["ROCKET", "Space launcher"],
  ["SAFARI", "Wildlife trip in Africa"],
  ["SCHOOL", "Place of learning"],
  ["SHADOW", "Dark shape cast by light"],
  ["SILVER", "Second-place medal"],
  ["SISTER", "Female sibling"],
  ["SPIDER", "Eight-legged web spinner"],
  ["SPRING", "Season after winter"],
  ["SUMMER", "Warmest season"],
  ["SUNSET", "Evening sky show"],
  ["TEMPLE", "Place of worship"],
  ["TICKET", "Pass to a show"],
  ["TOMATO", "Red fruit used in stew"],
  ["TRAVEL", "Go on a journey"],
  ["TURTLE", "Slow reptile with a shell"],
  ["VALLEY", "Low land between hills"],
  ["VELVET", "Soft, plush fabric"],
  ["WALLET", "Money holder"],
  ["WINDOW", "Glass pane in a wall"],
  ["WINTER", "Coldest season"],
  ["WIZARD", "Magician with a wand"],
  ["YELLOW", "Colour of a banana"],
  // 7 letters
  ["AIRPORT", "Place for take-off and landing"],
  ["ALPHABET", "A to Z"],
  ["BALLOON", "Party decoration filled with air"],
  ["BICYCLE", "Two-wheeler with pedals"],
  ["BLANKET", "Warm bed covering"],
  ["BROTHER", "Male sibling"],
  ["CAPTAIN", "Leader of a team or ship"],
  ["CHICKEN", "Bird that lays eggs"],
  ["CLIMATE", "Long-term weather"],
  ["COCONUT", "Hairy tropical fruit"],
  ["COMPASS", "Navigator's tool"],
  ["CONCERT", "Live music show"],
  ["COUNTRY", "Nigeria or Ghana"],
  ["CRYSTAL", "Clear gem-like mineral"],
  ["DIAMOND", "Hardest natural gem"],
  ["DOLPHIN", "Clever sea mammal"],
  ["ELEPHANT", "Largest land animal"],
  ["FEATHER", "Bird's covering"],
  ["FREEDOM", "Liberty"],
  ["GALAXY", "Milky Way, for one"],
  ["GIRAFFE", "Tallest animal"],
  ["HARMONY", "Musical agreement"],
  ["HOLIDAY", "Vacation"],
  ["JOURNEY", "Long trip"],
  ["KINGDOM", "Land ruled by a monarch"],
  ["KITCHEN", "Room for cooking"],
  ["LIBRARY", "Place to borrow books"],
  ["MORNING", "Start of the day"],
  ["MYSTERY", "Puzzle to be solved"],
  ["OCTOPUS", "Sea creature with eight arms"],
  ["PENGUIN", "Flightless bird in a tuxedo"],
  ["PICTURE", "Photo or painting"],
  ["PILLOW", "Head rest in bed"],
  ["PYRAMID", "Ancient Egyptian tomb"],
  ["RAINBOW", "Arc of colours after rain"],
  ["SANDALS", "Open summer shoes"],
  ["SCIENCE", "Study of the natural world"],
  ["SOLDIER", "Member of an army"],
  ["SPINACH", "Leafy green vegetable"],
  ["SUNRISE", "Dawn"],
  ["TEACHER", "Classroom leader"],
  ["THUNDER", "Rumble during a storm"],
  ["TREASURE", "Pirate's chest contents"],
  ["TRUMPET", "Brass instrument"],
  ["VILLAGE", "Small rural community"],
  ["VOLCANO", "Mountain that erupts"],
  ["WEATHER", "Rain or shine"],
  ["WEDDING", "Marriage ceremony"],
  // 8+ letters
  ["ADVENTURE", "Exciting experience"],
  ["BIRTHDAY", "Annual celebration of your arrival"],
  ["BUTTERFLY", "Insect that was a caterpillar"],
  ["CHAMPION", "Winner"],
  ["CHOCOLATE", "Sweet made from cocoa"],
  ["CROCODILE", "Large river reptile"],
  ["DAUGHTER", "Female child"],
  ["DINOSAUR", "Prehistoric reptile"],
  ["FIREWORK", "New Year's sky sparkler"],
  ["FOOTBALL", "The beautiful game"],
  ["HOMEWORK", "School tasks done at home"],
  ["HOSPITAL", "Place for the sick"],
  ["KANGAROO", "Hopping Australian animal"],
  ["MOUNTAIN", "Kilimanjaro or Everest"],
  ["NOTEBOOK", "Pad for writing"],
  ["PAINTING", "Mona Lisa, for one"],
  ["PINEAPPLE", "Spiky tropical fruit"],
  ["SANDWICH", "Filling between bread"],
  ["SNOWFLAKE", "Unique ice crystal"],
  ["STRAWBERRY", "Red fruit with seeds outside"],
  ["SUNFLOWER", "Tall yellow bloom"],
  ["SUNSHINE", "Warm daylight"],
  ["TELEPHONE", "Device for calls"],
  ["UMBRELLA", "Rain shield"],
  ["VACATION", "Holiday"],
  ["WATERFALL", "Cascade like Victoria Falls"],
];
